# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20190928_0540'),
        ('Support', '0002_queryanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='group',
        ),
        migrations.AddField(
            model_name='query',
            name='bundleGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundleGroup', to='LMS.BundleGroup'),
        ),
        migrations.AddField(
            model_name='query',
            name='courseGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseGroup', to='LMS.CourseGroup'),
        ),
    ]
