# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0004_query_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='query',
            name='bundleGroup',
        ),
    ]
