# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-30 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0006_auto_20190930_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='description',
        ),
    ]
