# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0007_remove_query_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
