# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_time_taken', models.FloatField(blank=True, default=0.0, null=True)),
                ('quiz_percentile', models.FloatField(blank=True, default=0.0, null=True)),
                ('Easy_percentile', models.FloatField(blank=True, default=0.0, null=True)),
                ('Intermediate_percentile', models.FloatField(blank=True, default=0.0, null=True)),
                ('Difficult_percentile', models.FloatField(blank=True, default=0.0, null=True)),
                ('Quiz_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Chapter')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Test')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
