# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0003_auto_20190928_0540'),
        ('LMS', '0005_auto_20190928_0540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Course'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='user',
            field=models.ManyToManyField(to='LMS.RegisteredCourse'),
        ),
        migrations.AddField(
            model_name='bundlegroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Bundle'),
        ),
        migrations.AddField(
            model_name='bundlegroup',
            name='user',
            field=models.ManyToManyField(to='LMS.RegisteredBundle'),
        ),
    ]
