# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_auto_20190928_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundlegroup',
            old_name='course',
            new_name='bundle',
        ),
    ]
