# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_remove_pretest_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult')], default='Easy', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='mcqtag', to='LMS.Tags'),
        ),
    ]
