# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_auto_20191012_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timegiven',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
