# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_auto_20191022_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresults',
            name='time',
        ),
        migrations.AddField(
            model_name='assignmentresults',
            name='timetaken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='timegiven',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
