# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_auto_20191028_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
