# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_subtopic_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('content', models.TextField(blank=True, max_length=100, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='topic',
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='mcqtag', to='LMS.SubTag'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
