# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0019_auto_20191125_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtag',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.Topic'),
        ),
    ]
