# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0022_auto_20191125_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ans_submit',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='corct_ans',
            field=models.CharField(max_length=100000),
        ),
    ]
