# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0023_auto_20191126_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='correct_ans',
            field=models.BooleanField(default=False),
        ),
    ]
