# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0024_testcases_correct_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='correct_ans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
