# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-10 18:18
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0025_auto_20191210_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='tags',
            field=jsonfield.fields.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
