# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-10 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0026_testcases_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='tags',
            new_name='ans_choice',
        ),
    ]
