# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0027_auto_20191210_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='testOutput',
            new_name='testCase',
        ),
    ]
