# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0029_assignmentresults_attemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
