# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-13 11:30
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0030_testcases_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=jsonfield.fields.JSONField(blank=True, max_length=2000, null=True),
        ),
    ]
