# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0031_problem_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='workshop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='conditions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
