# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0032_auto_20191214_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rewards',
            field=models.IntegerField(default=5),
        ),
    ]
