# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0033_problem_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresults',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
    ]
