# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0035_quizresult_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresults',
            name='ans_records',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
