# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0036_auto_20200121_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresults',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
